import {
  lightBlue,
  orange,
  green,
  grey,
  purple,
  red,
  pink,
  deepPurple,
  indigo,
  blue,
  cyan,
  teal,
  lightGreen,
  lime,
  yellow,
  amber,
  deepOrange,
  brown,
  blueGrey,
} from "@mui/material/colors";

// export const colors = {
//   lightBlue: { value: lightBlue, name: "Light Blue" },
//   orange: { value: orange, name: "Orange" },
//   green: { value: green, name: "Green" },
//   grey: { value: grey, name: "Grey" },
//   purple: { value: purple, name: "Purple" },
//   red: { value: red, name: "Red" },
//   pink: { value: pink, name: "Pink" },
//   deepPurple: { value: deepPurple, name: "Deep Purple" },
//   indigo: { value: indigo, name: "Indigo" },
//   blue: { value: blue, name: "Blue" },
//   cyan: { value: cyan, name: "Cyan" },
//   teal: { value: teal, name: "Teal" },
//   lightGreen: { value: lightGreen, name: "Light Green" },
//   lime: { value: lime, name: "Lime" },
//   yellow: { value: yellow, name: "Yellow" },
//   amber: { value: amber, name: "Amber" },
//   deepOrange: { value: deepOrange, name: "Light Blue" },
//   brown: { value: brown, name: "Brown" },
//   blueGrey: { value: blueGrey, name: "Blue Grey" },
// };

export const colors = [
  { value: lightBlue, name: "Light Blue" },
  { value: orange, name: "Orange" },
  { value: green, name: "Green" },
  { value: grey, name: "Grey" },
  { value: purple, name: "Purple" },
  { value: red, name: "Red" },
  { value: pink, name: "Pink" },
  { value: deepPurple, name: "Deep Purple" },
  { value: indigo, name: "Indigo" },
  { value: blue, name: "Blue" },
  { value: cyan, name: "Cyan" },
  { value: teal, name: "Teal" },
  { value: lightGreen, name: "Light Green" },
  { value: lime, name: "Lime" },
  { value: yellow, name: "Yellow" },
  { value: amber, name: "Amber" },
  { value: deepOrange, name: "Deep Orange" },
  { value: brown, name: "Brown" },
  { value: blueGrey, name: "Blue Grey" },
];
